name: Deploy to EC2

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Run the deployment on a Ubuntu runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Checkout the repository

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_PRIVATE_KEY }}  # Use the private key from GitHub secrets

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@44.202.190.212 << 'EOF'
          cd /var/www/html
          git pull origin main  # Pull the latest changes
          cd react-frontend
          npm install
          npm run build
          mv build/* /var/www/html
          sudo systemctl restart httpd  # Restart Apache to apply changes
        EOF
